

"use client"; // 👈 this makes it a Client Component

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes'

import { SessionProvider } from "next-auth/react"
import type { Session } from "next-auth";
import { Provider } from "react-redux";
import NextTopLoader from "nextjs-toploader";

  import { ToastContainer, toast } from 'react-toastify';
  

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session?: Session | null;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >



        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        > 
          <SessionProvider session={session} >
            {/* <Provider store={store}> */}
             <NextTopLoader   height={3}  />

            {children}
             <ToastContainer />
            {/* </Provider> */}
          </SessionProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
